FROM openjdk:8-jdk-alpine
WORKDIR /home
COPY target/node1-1.0-SNAPSHOT-jar-with-dependencies.jar node1-1.0-SNAPSHOT-jar-with-dependencies.jar
CMD ["java", "-jar", "node1-1.0-SNAPSHOT-jar-with-dependencies.jar"]
