FROM openjdk:8-jdk-alpine
WORKDIR /home
COPY target/node2-1.0-SNAPSHOT-jar-with-dependencies.jar node2-1.0-SNAPSHOT-jar-with-dependencies.jar
CMD ["java", "-jar", "node2-1.0-SNAPSHOT-jar-with-dependencies.jar"]
