version: '2'

services:
  client:
    image: client
    build: ./client
    container_name: client_app
    depends_on:
      - "node1"
      - "node2"
      - "node3"
    networks:
      main:
        aliases:
          - client

  node1:
    image: node1
    build: ./node1
    container_name: node1app
    networks:
      main:
        aliases:
          - no1

  node2:
    image: node2
    build: ./node2
    container_name: node2app
    networks:
      main:
        aliases:
          - no2

  node3:
    image: node3
    build: ./node3
    container_name: node3app
    networks:
      main:
        aliases:
          - no3

networks:
  main:
    driver: bridge
